_target_: src.models.cifar100_module.CIFAR100Module

feature:
  # [repeat, module, args]
  # Conv : [out, kernel, stride, padding, groups, activation]
  # MaxPool : [kernel, stride]
  [
    [1, Conv, [64, 3, 1, 1, 1, "ReLU"]],
    [1, MaxPool, [2, 2]],
    [1, Conv, [128, 3, 1, 1, 1, "ReLU"]],
    [1, MaxPool, [2, 2]],
    [2, Conv, [256, 3, 1, 1, 1, "ReLU"]],
    [1, MaxPool, [2, 2]],
    [2, Conv, [512, 3, 1, 1, 1, "ReLU"]],
    [1, MaxPool, [2, 2]],
    [2, Conv, [512, 3, 1, 1, 1, "ReLU"]],
    [1, MaxPool, [2, 2]],
  ]
# criterion: AdaptiveLogitAdjustmentLoss
lr: 0.001
weight_decay: 0.0005
init_weights: True
num_classes: 100