
wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "test"
  name: ${name}
  save_dir: ./wandb/
  offline: False
  id: null
  entity: "test"
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
