#@package _global_

defaults:
  - _self_
  - datamodule: cifar100.yaml
  - model: simple_conv_net.yaml
  - callbacks: default.yaml
  - logger: null
  - trainer: default.yaml
  - log_dir: default.yaml


  - experiment: null
  
  - debug: null

  - hparams_search: null

  - optional local: default.yaml

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/cifar100/
print_config: True

ignore_warnings: True

train: True

test: False

seed: 42

name: "default"
